[project]
name = "secretary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.0.19",
    "radicale",
]

[tool.uv.sources]
radicale = { url = "https://github.com/Kozea/Radicale/archive/master.tar.gz" }
